const Sdata=[
    {
        name:"nabin",
        title:"music",
        id:1,
        subject:["Math","English","Science"],//array display

        //arrayofobject 
        data:[
            {
                name:"rajat",
                title:"singer",
                id:1
            },
            {
                name:"abishek",
                title:"swimmer",
                id:2
            }
        ],
        //object
        car:{
            name:"toyota",
            price:40
        }

    },   
    
    {
        name:"sujan",
        title:"swimming",
        id:2,
        subject:["Math","English","Science"],
        data:[
            {
                name:"rajat",
                title:"singer",
                id:1
            },
            {
                name:"abishek",
                title:"swimmer",
                id:2
            }
        ],
        car:{
            name:"toyota",
            price:40
        }
    },
    {
        name:"rahul",
        title:"dance",
        id:3,
        subject:["Math","English","Science"],
        data:[
            {
                name:"rajat",
                title:"singer",
                id:1
            },
            {
                name:"abishek",
                title:"swimmer",
                id:2
            }
        ],
        car:{
            name:"toyota",
            price:40
        }
    },
    {
        name:"hari",
        title:"rap",
        id:4,
        subject:["Math","English","Science"],
        data:[
            {
                name:"rajat",
                title:"singer",
                id:1
            },
            {
                name:"abishek",
                title:"swimmer",
                id:2
            }
        ],
        car:{
            name:"toyota",
            price:40
        }
    }
]

export default Sdata;